name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-12, macos-11]
        include:
          - os: ubuntu-22.04
            container:
              image: ghcr.io/homebrew/ubuntu22.04:master
              options: --user=linuxbrew -e GITHUB_ACTIONS_HOMEBREW_SELF_HOSTED
            workdir: /github/home 
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-

      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      - run: brew test-bot --only-tap-syntax

      - name: Check umask, permissions
        run: |
          echo $PWD
          umask
          ls -larthR
          ls -larthR $(brew --cellar)
          
         
#      - run: brew test-bot --debug --only-formulae --only-json-tab --root-url=https://ghcr.io/v2/drbenmorgan/geant4
#        if: github.event_name == 'pull_request'

      # Try and get to just bottling step
      - name: Try bottle
        run: |
          id
          ls -larthR $(brew --cellar)
          brew fetch --retry drbenmorgan/geant4/g4ensdfstate --build-bottle --force
          brew install --only-dependencies --verbose --build-bottle drbenmorgan/geant4/g4ensdfstate
          brew install --verbose --build-bottle drbenmorgan/geant4/g4ensdfstate
          ls -larthR $(brew --cellar)
          mkdir testdir
          ls -larthR
          brew audit drbenmorgan/geant4/g4ensdfstate --online --git --skip-style
          brew bottle --verbose --json drbenmorgan/geant4/g4ensdfstate --root-url=https://ghcr.io/v2/drbenmorgan/geant4 --only-json-tab
          brew bottle --merge --write --no-commit ./g4ensdfstate--2.3_3.*.bottle.json
          tar -tvf ././g4ensdfstate--2.3_3.*.bottle.tar.gz
        if: github.event_name == 'pull_request'
        
      - name: Check umask, permissions after bottling
        run: |
          echo $PWD
          umask
          ls -larthR
          ls -larthR $(brew --cellar)

      - name: Upload bottles as artifact
        if: always() && github.event_name == 'pull_request'
        uses: actions/upload-artifact@main
        with:
          name: bottles
          path: '*.bottle.*'
